# Generated by Django 4.0.4 on 2023-06-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_user_gender_alter_useraddress_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
