# Generated by Django 4.2.2 on 2023-06-17 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_first_name_alter_user_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercountrystate',
            name='user_country',
        ),
        migrations.RemoveField(
            model_name='useraddress',
            name='user_country_state',
        ),
        migrations.AddField(
            model_name='useraddress',
            name='country',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='postal_code',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='state',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/user/profile'),
        ),
        migrations.DeleteModel(
            name='UserCountry',
        ),
        migrations.DeleteModel(
            name='UserCountryState',
        ),
    ]
