# Generated by Django 4.2.2 on 2023-07-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_usercountrystate_user_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofileimage',
            name='image',
            field=models.CharField(default='', max_length=200),
        ),
    ]
