# Generated by Django 4.2.2 on 2023-06-06 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Merchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='merchant', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('merchant_plan_listings', models.IntegerField()),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(max_length=2000)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/merchant_store_media/logos/')),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images/merchant_store_media/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images/merchant_store_media/departments/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='merchants.merchantstore')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantSubcription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to='merchants.merchant')),
                ('merchant_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='merchants.merchantplan')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='merchants.merchantstore')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreDepartmentView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='merchants.merchantstoredepartment')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPlanPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField()),
                ('description', models.CharField()),
                ('price', models.FloatField()),
                ('stripe_price_key', models.CharField()),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plan_prices', to='merchants.merchantplan')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantPlanFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField()),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='merchants.merchantplan')),
            ],
        ),
    ]
