# Generated by Django 4.0.4 on 2023-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantplan',
            name='description',
            field=models.CharField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='merchantplan',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchantplanfeature',
            name='title',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='merchantplanprice',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='merchantplanprice',
            name='stripe_price_key',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchantplanprice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='merchantplanprice',
            name='uid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantstore',
            name='uid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='merchantstoredepartment',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
