# Generated by Django 4.0.4 on 2023-06-07 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantplan',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='merchantplanprice',
            name='uid',
        ),
    ]
