# Generated by Django 4.2.2 on 2023-06-21 17:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0003_remove_merchantplan_uid_remove_merchantplanprice_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='MerchantStoreCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('banner_image', models.ImageField(blank=True, null=True, upload_to='images/merchant_store_media/categories/banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='merchants.merchantstore')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreCategoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store_category', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='views', to='merchants.merchantstorecategory')),
            ],
        ),
        migrations.RemoveField(
            model_name='merchantstoredepartmentview',
            name='merchant_store_department',
        ),
        migrations.DeleteModel(
            name='MerchantStoreDepartment',
        ),
        migrations.DeleteModel(
            name='MerchantStoreDepartmentView',
        ),
    ]
