# Generated by Django 4.2.2 on 2023-06-21 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_merchantstorecategory_merchantstorecategoryview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantplan',
            name='merchant_plan_listings',
        ),
        migrations.AddField(
            model_name='merchantplan',
            name='product_listings',
            field=models.IntegerField(default=0),
        ),
    ]
