# Generated by Django 4.2.2 on 2023-06-23 18:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0008_merchantstore_stripe_account_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantstore',
            name='stripe_account_id',
            field=models.CharField(blank=True, max_length=120, unique=True),
        ),
        migrations.CreateModel(
            name='MerchantPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_pm_id', models.CharField(max_length=120)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='payment_methods', to='merchants.merchant')),
            ],
        ),
    ]
