# Generated by Django 4.2.2 on 2023-06-26 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0009_alter_merchantstore_stripe_account_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchantsubcription',
            name='stripe_sub_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
