# Generated by Django 4.2.2 on 2023-07-02 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0010_merchantsubcription_stripe_sub_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchantstore',
            name='banner_image',
        ),
        migrations.RemoveField(
            model_name='merchantstore',
            name='logo',
        ),
        migrations.RemoveField(
            model_name='merchantstorecategory',
            name='banner_image',
        ),
        migrations.CreateModel(
            name='MerchantStoreLogo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='merchants.merchant')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreCategoryBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store_category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='merchants.merchantstore')),
            ],
        ),
        migrations.CreateModel(
            name='MerchantStoreBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.CharField(default='', max_length=200)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('merchant_store', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='merchants.merchant')),
            ],
        ),
    ]
