# Generated by Django 4.2.2 on 2023-07-03 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0011_remove_merchantstore_banner_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantstorelogo',
            name='merchant_store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='logo', to='merchants.merchantstore'),
        ),
    ]
