# Generated by Django 4.2.2 on 2023-07-03 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0012_alter_merchantstorelogo_merchant_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchantstorebanner',
            name='merchant_store',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='merchants.merchantstore'),
        ),
        migrations.AlterField(
            model_name='merchantstorecategorybanner',
            name='merchant_store_category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='banner', to='merchants.merchantstorecategory'),
        ),
    ]
