# from merchants.tests.merchant_center_test_views.merchant_views import TestMCMerchantViewSet
# from merchants.tests.merchant_center_test_views.merchant_payment_method_views import TestMCMerchantPaymentMethodViewSet
# from merchants.tests.merchant_center_test_views.merchant_subscription_views import TestMCMerchantSubscriptionViewSet
# from merchants.tests.merchant_center_test_views.merchant_plan_views import TestMCMerchantPlanViewSet
# from merchants.tests.merchant_center_test_views.merchant_store_views import TestMCMerchantStoreViewSet
# from merchants.tests.merchant_center_test_views.merchant_store_logo_views import TestMCMerchantStoreLogoViewSet
# from merchants.tests.merchant_center_test_views.merchant_store_banner_views import TestMCMerchantStoreBannerViewSet
from merchants.tests.merchant_center_test_views.merchant_store_category_views import TestMCMerchantStoreCategoryViewSet