# Generated by Django 4.2.2 on 2023-06-18 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProductSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category_product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.categoryproductspecification')),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryProductSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.subcategoryproductspecification')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySectionProductSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_section', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='product_specification', to='categories.subcategorysection')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySectionProductSpecificationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_section_product_specification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='categories.subcategorysectionproductspecification')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySectionProductSpecificationItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_section_product_specification_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='categories.subcategorysectionproductspecificationitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySectionCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/category_media/subcategory_sections/cover_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='categories.subcategorysection')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategorySectionBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/category_media/subcategory_sections/banner_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='categories.subcategorysection')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryProductSpecificationItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory_product_specification_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='categories.subcategoryproductspecificationitem')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/category_media/subcategories/cover_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='SubcategoryBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/category_media/subcategories/banner_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('subcategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='categories.subcategory')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='views', to='categories.category')),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='categories.subcategory')),
                ('subcategory_section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='views', to='categories.subcategorysection')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProductSpecificationItemOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category_product_specification_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='categories.categoryproductspecificationitem')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryCoverImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover_image', models.ImageField(upload_to='images/category_media/main/cover_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cover_images', to='categories.category')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryBannerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(upload_to='images/category_media/main/banner_images/')),
                ('is_active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated', models.DateTimeField(auto_now_add=True, null=True)),
                ('deleted', models.DateTimeField(null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banner_images', to='categories.category')),
            ],
        ),
    ]
