# Generated by Django 4.0.4 on 2023-06-07 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentbannerimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentcoverimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentproductspecification',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsectionbannerimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsectioncoverimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsectionproductspecification',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionbannerimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectioncoverimage',
            name='uid',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionproductspecification',
            name='uid',
        ),
    ]
