# Generated by Django 4.2.2 on 2023-06-18 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0002_remove_departmentbannerimage_uid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='departmentbannerimage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentcoverimage',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentproductspecification',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentproductspecificationitem',
            name='department_product_specification',
        ),
        migrations.RemoveField(
            model_name='departmentproductspecificationitemoption',
            name='department_product_specification_item',
        ),
        migrations.RemoveField(
            model_name='departmentsection',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentsectionbannerimage',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='departmentsectioncoverimage',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='departmentsectionproductspecification',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='departmentsectionproductspecificationitem',
            name='department_section_product_specification',
        ),
        migrations.RemoveField(
            model_name='departmentsectionproductspecificationitemoption',
            name='department_section_product_specification_item',
        ),
        migrations.RemoveField(
            model_name='departmentsubsection',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionbannerimage',
            name='department_sub_section',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectioncoverimage',
            name='department_sub_section',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionproductspecification',
            name='department_sub_section',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionproductspecificationitem',
            name='department_sub_section_product_specification',
        ),
        migrations.RemoveField(
            model_name='departmentsubsectionproductspecificationitemoption',
            name='department_sub_section_product_specification_item',
        ),
        migrations.RemoveField(
            model_name='departmentview',
            name='department',
        ),
        migrations.RemoveField(
            model_name='departmentview',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='departmentview',
            name='department_sub_section',
        ),
    ]
