# Generated by Django 4.0.4 on 2023-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemfulfillment',
            name='shipping_label',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
