# Generated by Django 4.0.4 on 2023-06-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='isbn',
            field=models.CharField(blank=True, max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='uid',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
    ]
