# Generated by Django 4.0.4 on 2023-06-07 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariantitemimage',
            name='uid',
        ),
    ]
