# Generated by Django 4.2.2 on 2023-06-18 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
        ('products', '0003_remove_productvariantitemimage_uid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='department',
        ),
        migrations.RemoveField(
            model_name='product',
            name='department_section',
        ),
        migrations.RemoveField(
            model_name='product',
            name='department_sub_section',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategory'),
        ),
        migrations.AddField(
            model_name='product',
            name='subcategory_section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='categories.subcategorysection'),
        ),
    ]
